- deploy/crds/chaosengine.yaml
- deploy/crds/chaosexperiment.yaml
- deploy/crds/chaosgraph.yaml
- deploy/crds/litmuschaos_v1alpha1_chaosengine_cr.yaml
- deploy/crds/litmuschaos_v1alpha1_chaosexperiment_cr.yaml
- deploy/crds/litmuschaos_v1alpha1_chaosgraph_crd.yaml
- deploy/crds/litmuschaos_v1alpha1_chaostemplate_cr.yaml
- Consists of custom resource spec updates into the placeholders provided by operator-sdk
> (feat)(cr) define the chaos custom resource specifications

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Chandan Kumar <chandan.kumar@mayadata.io>
> chore(github templates): add template for issue and PullRequest

- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/kubernetes/containers/build.go
- pkg/kubernetes/containers/containers.go
- pkg/kubernetes/pod/build.go
- pkg/kubernetes/pod/pod.go
- pkg/kubernetes/service/build.go
- pkg/kubernetes/service/service.go
- Implements  the "builder pattern" a way to construct the kubernetes specs for secondary resources `engine-runner` & `engine-monitor`. Provides a way to define resources in a cleaner and simpler manner.
**Checklist:**
> (refactor)operator: implement builder pattern for building secondary resources

- deploy/operator.yaml
- deploy/rbac.yaml
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- Accepts service account for chaos operations from chaosengine spec. This will enable users to define the scope & capability of the chaos-runner. 
- Update the operator & rbac manifests to ensure the default working namespace of operator is litmus
NOTE: Ensure that the service account provided has sufficient privileges to access the resources belonging to group litmuschaos.io 
**Checklist:**
> (feat)operator: accept service account for chaos operations

- pkg/controller/chaosengine/chaosengine_controller.go
This change is required to scrape the metrics exporter pod by Prometheus.
Note: Prometheus is looking for the pod with label `chaos-exporter`.
**Checklist:**
> fix:(area/monitoring) Add unique label for exporter pod

- .circleci/config.yml
- buildscripts/push
- deploy/operator.yaml
- Homogenises the image tagging practice across litmuschaos components chaos-operator, chaos-exporter & ansible-runner.  
- Uses `ci` tag for images built on updates to master. Released images use `github release tag` and `latest`. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/litmuschaos/litmus/issues/919
- The BDD tests executed on minikube in the CircleCi VM/Docker-Machine make use of the same tag with which it is built : `ci` for their execution with the `imagePullPolicy: ifNotPresent` on the deploy/operator.yaml. 
**Checklist:**
> (refactor)build: ensure 'latest' tag corresponds to release builds

- pkg/controller/resource/daemonset.go
- pkg/controller/resource/deployment.go
- pkg/controller/resource/resource.go
- pkg/controller/resource/statefulset.go
- Add support to induce chaos for daemonset
-  Fix the error in the calculation logic of chaos enabled application count
**Which issue this PR fixes**: fixes https://github.com/litmuschaos/litmus/issues/880
**Checklist:**
> (feat): Add daemonset support for chaos testing

- deploy/operator.yaml
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/types/types.go
This PR will help in fetching the  image of chaos-runner pod and monitor pod from chaos-engine  spec and if it is not present in chaos-engine spec then it will take images from chaos-operator envs and in the worst case if images are not present in both chaos-engine spec and chaos-operator envs then it will set default values.
**Checklist:**
> Added operator default ENV for chaos runner/monitor image

- pkg/controller/resource/daemonset.go
- pkg/controller/resource/deployment.go
- pkg/controller/resource/resource.go
- pkg/controller/resource/statefulset.go
- Optimize the total chaos count logic
- **Explanation**: If the `5` application have the same label then for loop will run only once and if he got the chaos count greater than `1` then the loop will break with the error `too many chaos counts`
- Refactor the function `CheckDeploymentAnnotation`, `CheckDaemonSetAnnotation` and `CheckStatefulSetAnnotation` according to BCH rule
**Which issue this PR fixes**: #92 
**Checklist:**
> (optimize): Update the total chaos count logic

- Makefile
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/apis/litmuschaos/v1alpha1/zz_generated.deepcopy.go
- pkg/client/clientset/versioned/clientset.go
- pkg/client/clientset/versioned/fake/clientset_generated.go
- pkg/client/clientset/versioned/typed/litmuschaos/v1alpha1/litmuschaos_client.go
- pkg/controller/chaosengine/chaosengine_controller.go
Added support for litmuschaos/chaos-executor:ci (image)
New ChaosEngine spec for invoking the go-Executor 
```
chaos:~$ cat chaosEngine.yaml 
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
name: engine-nginx
namespace: dance
spec:
jobCleanUpPolicy: retain
monitoring: false
components:
runner:
image: "litmuschaos/chaos-executor:ci"
type: "go"
appinfo: 
appns: dance 
applabel: "app=nginx" 
appkind: deployment
chaosServiceAccount: nginx 
experiments:
- name: pod-delete
spec:
components:
- name: TARGET_CONTAINER
value: nginx
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: …
> (feat)GoExecutor: Added support to run experiment via GoExecutor

- deploy/crds/chaosengine_crd.yaml
- deploy/crds/chaosexperiment_crd.yaml
- The chaosExperiment & chaosEngine CRDs are dev/user facing custom resources in LitmusChaos. These determine the execution and outcome of the chaos experiment & thus need validation at a pre-deployment level to prevent unnecessary runtime failures
- The chaos-executor (esp. the ansible executor) today has complex validation logic that is not needed provided the CRD schema is strictly enforced. One way to achieving this is with the OpenAPI specification based schema validation.  
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/litmuschaos/litmus/issues/1002
**Special notes …
> (enhancement)crds: add openapi specification based schema validation for chaos CRDs

- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/types/types.go
-  Added chaosType in engine spec - infra/app
-  Skip the annotation check for infra chaos
**engine yaml after changes**
```
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
name: engine-nginx
namespace: default
spec:
jobCleanUpPolicy: retain
chaosType: "infra" # app/infra      <--- Add chaosType here
monitoring: false
appinfo: 
appns: default 
applabel: "run=myserver" 
appkind: deployment
chaosServiceAccount: nginx 
experiments:
- name: container-kill
spec:
components:
- name: TARGET_CONTAINER
value: nginx
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1012 …
> (feat): Add chaosType [app/infra] in engine spec

- .gitignore
- cmd/manager/main.go
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/resource/daemonset.go
- pkg/controller/resource/deployment.go
- pkg/controller/resource/statefulset.go
- Refactor according to the BCH rule 
- Current score is 10/10 (But still require some refactoring)
**Which issue this PR fixes**: fixes https://github.com/litmuschaos/litmus/issues/1041
- Trying to keep the PR sort for easy review process
```
{"level":"info","ts":1577944152.6691897,"logger":"cmd","msg":"Go Version: go1.13.4"}
{"level":"info","ts":1577944152.6692498,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1577944152.6692646,"logger":"cmd","msg":"Version of operator-sdk: v0.12.0"}
{"level":"info","ts":1577944152.6692677,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1577944153.5137193,"logger":"leader","msg":"No pre-existing lock was found."} …
```
> (refactor): Refactor according to the BCH rule 

- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/utils/utils.go
- pkg/controller/watcher/watcher.go
```
- Added recorder for operator
- Added string to start/stop the chaosengine
- Removed owner Reference for the resources
- Added labels for UUID
- Auto removal for runner and monitor
- Capture DeleteTimeStamp and remove resources
- Addition of Finalizers
```
Command needed to patch chaosEngine: 
`kubectl patch chaosengine name.of.chaos.engine -n chaos.engine.namespace --type merge --patch '{"spec":{"engineStatus":"stop"}}'`
**Checklist:**
> (feat) chaos-operator: Added Abort functionality

- deploy/operator.yaml
- pkg/controller/types/types.go
- To understand this change and loogic behind it, please take a look at: `chaosengine_controller.go +571`
**Checklist:**
> (fix) chaos-operator: Changed Runner Default ENV to use go-executor

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- The controller patches the engineState with "initialized, stopped" to prevent undesirable reconcile once the respective action has been taken on the user options "active|stop" 
- These states need to be added into the CRD validation schema, failing which - once the runner/monitor are created, the engine cannot be patched afterwards. 
**Checklist:**
> (fix) update additional states for engine

- Makefile
- pkg/controller/chaosengine/chaosengine_controller.go
This PR is to add the name and namespace of the chaosEngine CR events,
- kubectl describe logs: 
```
Name:         engine
Namespace:    litmus
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
{"apiVersion":"litmuschaos.io/v1alpha1","kind":"ChaosEngine","metadata":{"annotations":{},"name":"engine","namespace":"litmus"},"spec":{"a...
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosEngine
Metadata:
Creation Timestamp:  2020-02-20T10:15:07Z
Generation: …
```
> (feat) Added Name and Namespace of ChaosEngine in CR events

- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- Removed possible states "initialized" and "stopped" from engineState (these states are added by the controller to avoid repeated reconcile operations. However, this is a spec item & should not be modified by the controller)
- Added EngineStatus in Status component of ChaosEngine for above purposes
Needs/Use-cases/Motivation for Status vs State:
- The spec.engineState is now the one which the user patches and Status is the internal status of the chaos-operator.
- Separation of state (user-side) and …
> (feat) Added engineStatus field in ChaosEngine Status

- Makefile
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- This PR is for adding functionality to pass Args and Commands for the RunnerPod    
- Added fields for passing the arguments, and commands to the runner Pod for debug purposes.
- Added fields to pass imagePullPolicy
- Override the go command/args 
- Use default command/args (i.e., chaosengine doesn't override) 
-  Override the ansible command/args 
- Use default command/args (i.e., chaosengine doesn't override) 
- What is the CRD validation corresponding to this? 
- BDD corresponding to this (new / changes to existing one)  …
> (feat) Added functionality to pass the Args, Commands, and ImagePullPolicy for Runner Pod

- deploy/chaos_crds.yaml
- deploy/crds/chaosresult.yaml
- deploy/crds/chaosresults_crd.yaml
- Remove status subresource from the chaos-result
**Checklist:**
> refactor(chaos-result): Remove status subresource from the chaos-result

- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- tests/bdd/bdd_test.go
- Adds Logic to check JobCleanUpPolicy
- Adds const strings for JobCleanUpPolicy
- Adds Logic to fetch phase of runner pod
- Changes behaviour of resources deletion using JobCleanUpPolicy and runnerPod Phase. If the runner pod status  is completed, engineStatus is patched to completed and runner pod removed 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes 
https://github.com/litmuschaos/litmus/issues/1260
**Checklist:**
> (feat) Deletion of Chaos Resources after Completion of Chaos-Runner

- pkg/controller/chaosengine/chaosengine_controller.go
- Ensures that the runner pod removal in case of experiment completion workflow is subject to cleanUpPolicy. If it is  "retain", the runner pod is not removed. 
**Checklist:**
> (feat) Removal of Default Resources, only when JobCleanUpPolicy is set to Delete

- pkg/controller/chaosengine/chaosengine_controller.go
> (feat) Added support to update the experiment Statuses for Aborted Experiments

- .gitignore
- coverage.txt
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/resource/deploymentconfig.go
- pkg/controller/resource/resource.go
- pkg/dynamic/dynamic.go
- tests/bdd/bdd_test.go
- In this PR, we have converted the global EngineInfo variable, to local variable.
- There was an issue in chaos-operator where the client-go k8s api-server calls to perform CRUD operations on ChaosEngine, sometimes failed and caused chaos-operator error logs.
- This was because of change in resourceVersion of ChaosEngine resource, because both the Global Variable of EngineInfo, and local instances of EngineInfo were not in sync before make k8s client-go operations.
**Checklist:**
> (refactor) Changed scope of EngineInfo structure from Global to Local

- pkg/controller/chaosengine/chaosengine_controller.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #211 
-  Inhibits chaos when (with .spec.annotationCheck = "true" in engine): 
- No chaos annotation (litmuschaos.io/chaos: "true") set of  app spec
- Annotation value set to "false"
- Annotation value set to neither true/false
-  Runs chaos when: 
- .spec.annotationCheck is set to "false"
- .spec.annotationCheck is set to "true" & app is annotated with "litmuschaos.io/chaos: true"
**Checklist:**
> (fix)controller: propagate annotation check failure to reconciler

- deploy/chaos_crds.yaml
- deploy/crds/chaosexperiment_crd.yaml
- pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
- pkg/apis/litmuschaos/v1alpha1/zz_generated.deepcopy.go
- Adding the security context in the chaos experiment CR so that we can bypass those security context to the chaos-pod and create the chaos pod those features.
**Checklist:**
-   [x] Fixes litmuschaos/litmus#1594
-   [ ] Labelled this PR & related …
> feat(security-context): adding the security context in experiment CR

- .github/auto-merge.yml
- .github/workflows/main.yml
Signed-off-by: Udit Gaurav udit.gaurav@mayadata.io
This PR is for:
- Adding GitHub CI workflow for chaos operator repository which will run on demand operator BDDs before merging a PR. It will be helpful to test the PRs before merging. We can call a test using `/run-e2e-<testname>`.
- Adding merge label for an issue comment `/merge` which will be further taken by pro bot to merge the PR.
- Added link of the job as a result of the CI run. 
**Which issue this PR fixes**
fixes: https://github.com/litmuschaos/litmus/issues/1628 and https://github.com/litmuschaos/litmus/issues/1627
- Install [auto-merge-pro-bot](https://github.com/apps/probot-auto-merge) in this repository to merge a PR by checking `/merge` comment …
> chore(CI): Add GitHub CI to run on demand operator BDDs

- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- Enhances the ChaosEngine Status schema to hold more information about the experiment in terms of experiment name, runner launching this experiment & the experiment pod executing the chaos.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # (partially fulfills #250 )
**Checklist:**
- …
> (enhancement)types: enhance the engineStatus schema to hold more run details

- deploy/01-chaos-operator.yaml
- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- pkg/controller/chaosengine/chaosengine_controller.go
- Patches the engine status with appropriate status (stopped) along with right event messages to indicate that the chaos resources won't be launched in case of failed app identification
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # https://github.com/litmuschaos/litmus/issues/1828
**Checklist:**
-   [ ] PR messages has breaking changes …
> (fix)controller: fix engine status updates upon app filter failure

- pkg/controller/chaosengine/chaosengine_controller.go
- Adds default Kubernetes pattern of looking for target application in the same namespace where the chaosengine resource is created, if the `.spec.appinfo.appns` is not explicitly specified. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #255 
- We haven't made the attribute omitempty, just so we get a bit more visibility in terms of spec/debug. Takes it as an empty "" irrespective of this (we will see it empty in the spec now). Open to thoughts/changes. 
**Checklist:**
-   [ ] Labelled this PR & related issue with …
> (enhance)controller: default to the chaosengine resource namespace if app namespace is not specified

- .circleci/config.yml
- Makefile
- build/Dockerfile
- build/go-multiarch-build.sh
- buildscripts/push
- This PR is for the addition of multi-arch support for chaos-operator image. The current support for `amd64` and `arm64` is added and we can easily add more platform using the go-multiarch-build.sh script.
- circle-ci is also modified to setup `buildx`  which is used to create multi-arch image.
**Which issue this PR fixes** 
-  fixes: litmuschaos/litmus#1550
**Checklist:**
-   [X] Fixes #litmuschaos/litmus#1550
- …
> feat(multiarch): Add multi-arch support for chaos operator image

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- Adding the ability to provide appinfo as optional field in chaosengine.
**Checklist:**
-   [ ] …
> chore(appinfo): Add ability to provide appinfo as optional

- deploy/rbac.yaml
- tests/bdd/bdd_test.go
- tests/manifest/pod_delete_rbac.yaml
- This PR adds minimum permission to run chaosoperator
- An [e2e pipeline](https://gitlab.mayadata.io/litmuschaos/litmus-e2e/pipelines/12749) run with the given permission. 
**Checklist:**
-   [ ] Labelled this PR & related issue …
> chore(permission): Adds minimum permission for operator

- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/apis/litmuschaos/v1alpha1/zz_generated.deepcopy.go
- Adding an ability to provide resource requirements for the chaos pod via chaosengine.
```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
name: engine
spec:
engineStatus: "active"
annotationCheck: "false"
appinfo:
applabel: "run=nginx"
appns: "shubham"
components:
runner:
image: "shubh214/chaos-runner:ci"
imagePullPolicy: "Always"
jobCleanUpPolicy: 'retain'
chaosServiceAccount: litmus
monitoring: false
experiments:
- name: pod-network-loss
spec:
components:
resources:
requests:
cpu: 10m
memory: 100Mi 
limits:
cpu: 10m
memory: 100Mi
env:
- name: SEQUENCE
value: "parallel"
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
> chore(resourceRequirements): Adding resource requirements in chaos pod

- deploy/operator.yaml
- deploy/rbac.yaml
- pkg/controller/chaosengine/chaosengine_controller.go
- Adds standard, recommended Kubernetes labels to the chaos-runner 
**Checklist:**
- …
> (enhancement)runner: add standard kubernetes labels to chaos-runner

- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/chaosengine/chaosengine_controller_test.go
- This is for passing app kind information to chaos experiment. We pass app labe and app namespace but app kind was missing ENV. 
**Checklist:**
-   [ ] PR …
> chore(app_kind): Pass app kind information to experiment

- pkg/analytics/analytics.go
- pkg/analytics/uuid.go
- We are only setting this flag when we want to disable analytics. If the analytics is allowed then `ANALYTICS` flag is unset instead of setting `TRUE` value that's why changing this condition to match with `FALSE` instead of True value.
**Checklist:** …
> fix(analytics): Skip the clientUUID generation if ANALYTICS is set to False

- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- Adding OnChaos mode in all the probes. Its lifetime is the same as the chaos duration. It will help for those cases where certain conditions before and during chaos are not the same or we want to perform some steps during the chaos only.
**Checklist:** …
> chore(onChaos-Mode): Adding onChaos mode in probes

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- deploy/rbac.yaml
- pkg/controller/resource/argorollouts.go
- pkg/controller/resource/daemonset.go
- pkg/controller/resource/deployment.go
- pkg/controller/resource/deploymentconfig.go
- pkg/controller/resource/resource.go
- pkg/controller/resource/resource_test.go
- pkg/controller/resource/statefulset.go
- Supports chaos on [argo rollouts](https://argoproj.github.io/argo-rollouts/) resource to facilitate chaos as a step in blue-green/canary deployments
- Also fixes a bug in the deploymentconfig list function in resource pkg
**Checklist:**
-   [ ] PR messages has breaking changes related …
> (enhancement)resources: add argo rollouts as a supported parent resource for chaos

- .github/workflows/main.yml
- This PR is for updating GitHub action e2e. A tested run is at : - https://github.com/uditgaurav/test-chaos-operator/runs/1498737228?check_suite_focus=true
- Also removes the `/merge` command due to security reasons.
**Checklist:**
-   [ ] PR messages has breaking changes related …
> chore(e2e): Update GitHub Actions e2e

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- pkg/controller/chaosengine/chaosengine_controller.go
This PR fixes the following issues in the reconcile flow of the chaos operator: 
- Creating a **new** chaosengine resource with `.spec.engineState` set to `stop` (this is a model being used by some users to *pre-install* the engine as part of a package, with experiments being triggered when needed via a patch to state: active) causes the reconciler to patch the `.status.engineStatus` to `stopped`. This is undesirable. Having it set to stopped causes a subsequent patch to engineState: active to be considered as a "Restart" (post abort or completion) which generates both the `RestartInProgress` as well as a "ChaosEngineInitialized" events.
The fix causes the status in such a case to remain empty/unset. …
> (fix)reconcile: fix incorrect sequence of events for engine restart

- deploy/chaos_crds.yaml
- deploy/crds/chaosexperiment_crd.yaml
- pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
Add a `type` field to the `hostFileVolumes` object on ChaosExperiments, to enable specifying different types when mounting hostPaths, such as CRI sockets
litmuschaos/litmus#2410 depends on this PR
**Checklist:**
> Add `type` definition to ChaosExperiment CRD hostFileVolumes object

- go.sum
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/chaosengine/chaosengine_controller_test.go
- pkg/controller/resource/argorollouts.go
- pkg/controller/resource/daemonset.go
- pkg/controller/resource/deployment.go
- pkg/controller/resource/deploymentconfig.go
- pkg/controller/resource/resource.go
- pkg/controller/resource/resource_test.go
- pkg/controller/resource/statefulset.go
- pkg/controller/types/types.go
- Earlier Chaos Operator allows only a single annotated application as a chaos candidate if the annotationCheck is set to true. With these changes, it will enable multiple annotated applications to be targeted as chaos candidates.
**Checklist:**
-   [x] Fixes #<issue number>
-   [ ] PR messages has breaking …
> feat(annotation): Enable the multiple app with annotation

- pkg/controller/chaosengine/chaosengine_controller.go
- Ensure that the `GracePeriodSeconds` is not set to 0 for the abort scenario. The intent of abort functionality is to kill/stop the chaos processes immediately - not remove the chaos pods/resources quickly. In experiments that involve injection of chaos processes into target/remote containers, the rollback routines are a bit more "involved" (there are routines that are executed upon receiving a SIGTERM) & need time to execute & succeed. Removing these pods immediately causes these rollback operations to remain incomplete - causing problems in the app environment. 
- This fix will allow for the pods to terminate gracefully by allowing the execution of the desired routines 
- This is a precursor to …
> (fix)controller: remove force options of chaos pods upon abort

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- Removing maxProperties field from openapi validator for chaosengine CRD
**Checklist:**
-   [ ] …
> fix(crds): Removing maxProperties field from openapi validator for chaosengine

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
HTTP API call timeout has been added for probe
Response timeout will bound the client for particular time to call API request
**Checklist:**
-   [x] Fixes #<issue number>
> ResponseTimeout for API Request call added for HttpProbe

- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/chaosengine/chaosengine_controller_test.go
- pkg/controller/resource/resource_test.go
- pkg/controller/types/types.go
App Label can be used:
- =
- ==
- !=
- in
- notin
- exists
fixes: #334 
Have tested with labels.
Engine Specification
```
spec:
appinfo:
appns: 'sock-shop'
applabel: 'app, name in (sock-shop, catalogue)'
appkind: 'deployment'
annotationCheck: 'true'
engineState: 'active'
chaosServiceAccount: litmus-admin
monitoring: true
jobCleanUpPolicy: 'retain'
components:
runner:
imagePullPolicy: Always
```
Workflow result:
```
custom-chaos-workflow-1615274891   Succeeded   52m
``` 
**Checklist:**
-   [x] Labelled this PR & related issue with `documentation` tag
-   [ ] PR …
> Added support for Equality-based and Set-based requirements for App Label

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- deploy/crds/chaosexperiment_crd.yaml
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
- pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- Adding support for the termination grace period seconds of the experiment & helper pod. Which can be provided at `.spec.experiments[*].spec.components.terminationGracePeriodSeconds` path inside chaosengine.
-  convert few other attributes from small case to the camel case
**Checklist:**
-   [ ] Labelled this PR & related issue with `breaking-changes` …
> chore(terminationGracePeriodSeconds): Adding support for the termination grace period seconds

- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/chaosengine/chaosengine_controller_test.go
- pkg/controller/resource/resource_test.go
- tests/bdd/bdd_test.go
Signed-off-by: Oum Kale <oumkale@chaosnative.com>
This PR: Monitoring will be independent of monitoring flag in engine. 
Use : No need to pass flag to see Prometheus metrics for experiments.
Files Updates:
- chaos_crds.yaml
- chaosengine_crd.yaml
- chaosengine_types.go 
- chaosengine_controller_test.go 
- bdd_test.go 
**Checklist:**
-   [x] PR messages has upgrade related …
> chore(engineMonitoringType): Removed Monitoring field from ChaosEngine. 

- deploy/chaos_crds.yaml
- deploy/crds/chaosexperiment_crd.yaml
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR adds the missing `imagePullPolicy` attribute in the chaos experiment CRD
**Checklist:**
-   [x] Fixes Bug
> Added imagaPullPolicy to chaos experiment crd

- pkg/analytics/analytics.go
- pkg/analytics/uuid.go
- pkg/controller/chaosengine/chaosengine_controller.go
- pkg/controller/utils/types.go
- pkg/controller/utils/utils.go
-  using the same user-id for analytics even if operator pod restarts
-  setting deployment UID as  clientUUID for analytics
**Checklist:**
-   [ ] PR …
> feat(analytics): using same user-id for analytics even if operator pod restarts

- deploy/rbac.yaml
Signed-off-by: Adarshkumar14 <adarsh.kumar@harness.io>
- With chaos-operator:2.11.0, `chaosengines/finalizers` resource permission is required for openshift deployment.
**Checklist:** …
> Adding cr required for the openshift deployment

- api/litmuschaos/v1alpha1/chaosengine_types.go
- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- Adds inherit_inputs field in cmdProbe/inputs.source to inherit experiment details in probe pod
**Checklist:**
- …
> Chore(cmd-probe): Adds inherit_inputs field in cmdProbe/inputs.source to inherit experiment details in probe pod

- api/litmuschaos/v1alpha1/chaosengine_types.go
- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
- Make probe retry optional in crds to support value 0 (retries)
- Rename DefaultAppHealthCheck to DefaultHealthCheck
**Checklist:**
-   [ ] PR messages has upgrade …
> Chore(probes): Make probe retry optional in crds to support value 0 (retries) AND rename defaultAppHealthCheck

- api/litmuschaos/v1alpha1/chaosengine_types.go
- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
This PR adds ResourceNames field which is a list of comma-separated resource names used to filter resources in k8s probe.
Related https://github.com/litmuschaos/litmus-go/issues/599
**Checklist:**
-   [ ] Labelled this PR & …
> feat: add resource names field in k8sprobe

- api/litmuschaos/v1alpha1/chaosresult_types.go
Adds a more appropriate status for chaos result upon probe failure within an experiment/fault. 
**Checklist:** …
> (enhancement)schema: additional statuses for result phase

- api/litmuschaos/v1alpha1/chaosengine_types.go
- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
> chore(unit): Adding units to the duration fields

- api/litmuschaos/v1alpha1/chaosengine_types.go
- api/litmuschaos/v1alpha1/zz_generated.deepcopy.go
- deploy/chaos_crds.yaml
- deploy/crds/chaosengine_crd.yaml
> Support  taints and tolerations for source cmd Probe

- .github/workflows/build.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- go.mod
- go.sum
- pkg/utils/utils.go
- pkg/utils/utils_fuzz_test.go
> add fuzz test for remove string utility function

- controllers/chaosengine_controller_test.go
- pkg/utils/volumeUtils.go
> chore(operator): Fix the lint for the unused fields

- build/Dockerfile
Migrate the base images of the chaos-operator container images of LitmusChaos from infra-alpine to ubi minimal.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4634 (https://github.com/litmuschaos/litmus/issues/4634)
**Checklist:**
-   [x] Fixes #4634
-   [ ] PR messages has upgrade related …
> UBI migration of Images - chaos-operator

- .github/CODEOWNERS
- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
- go.mod
> chore(go): upgrade the go version
