.gitignore

- Adds gitignore file to remove auto-generated binaries from operator-sdk
- Remove binaries pushed as part of previous commits 
**Checklist:**

(chore)(git): add .gitignore file and remove binaries from repo

---

README.md

Signed-off-by: Chandan Kumar <chandan.kumar@mayadata.io>
Added badge of following
- Codacy
- Go Report Card
- CII Best Practices

Add badges for codacy, go report card and cli best practice

---

pkg/apis/litmuschaos/v1alpha1/register.go

- Use constants in register.go for the api group name & Version so they can be reused 
when package is imported
**Checklist:**

(refactor)(autogenerated code) use constants in register.go

---

README.md

- Updates the README with the project details
**Checklist:**

(refactor)readme: update the readme

---

.circleci/config.yml
Makefile
buildscripts/push

- Adds CI to build & push the chaos-operator image to the docker repository
**Checklist:**

(chore)ci: add ci to the chaos-operator project

---

.circleci/config.yml
Makefile
buildscripts/push

- Decomposes the steps performed by operator-sdk as separate tasks 
- Decomposes the make/build process to sub-steps in order to support/ease both manual make & build/push via circle ci
- Uses the `remote docker env` feature in circle CI to enable building/pushing docker images while using a golang container for go build tasks (DinD)
**Checklist:**

(refactor)ci: fix ci issues

---

README.md

update readme with result description

---

.bettercodehub.yml

- Introduce bettercodehub profile to fix #23 
**Checklist:**

(chore)ci: include bettercodehub profile 

---

cmd/manager/main.go
pkg/apis/addtoscheme_litmuschaos_v1alpha1.go
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
pkg/controller/chaosengine/chaosengine_controller.go

- Changed all the logs to follow runtime/logr syntax
- Added tags to all the log object to access them in JSON format
**Checklist:**

(refactor)log: make the logs homogeneous (use structured logging throughout the controller) 

---

pkg/controller/chaosengine/chaosengine_controller.go

 (refactor)controller: add a struct to hold application info

---

pkg/controller/chaosengine/chaosengine_controller.go

Signed-off-by: Amit Bhatt amitbhatt818@gmail.com
**Checklist:**

(refactor)controller: rename vars and functions to adhere to go (verbose) standards

---

Makefile
pkg/controller/chaosengine/chaosengine_controller.go

Added Annotation Check for the chaos-operator
**Checklist:**
- [ .] Labelled this PR & related issue with `requires-upgrade` tag

(fix)controller: ensure the chaos annotation is set to true 

---

pkg/controller/chaosengine/chaosengine_controller.go

This commit will refactor the reconcile function like:
Created two functions 
1. engineRunnerPod() 
- engineRunnerPod checks if the engineRunner pod already exists or not, if it is already there then it returns otherwise this function creates an engineRunner Pod.
2. engineMonitorService ()
- engineMonitorservice checks if the engine monitor service already exist or not, if it is already there then it returns otherwise this function creates an engine monitor service
**Checklist:**

(refactor)controller: created function for engineRunnerPod and engineMonitorService

---

.bettercodehub.yml
pkg/controller/chaosengine/chaosengine_contoller_test.go
pkg/controller/chaosengine/chaosengine_controller.go

In this PR unit test is implemented for chaosengine_controller.
output of test -
```
=== RUN   TestNewRunnerPodForCR
=== RUN   TestNewRunnerPodForCR/Test_Positive
=== RUN   TestNewRunnerPodForCR/Test_Negative-1
=== RUN   TestNewRunnerPodForCR/Test_Negative-2_
=== RUN   TestNewRunnerPodForCR/Test_Negative-3_
--- PASS: TestNewRunnerPodForCR (0.00s)
--- PASS: TestNewRunnerPodForCR/Test_Positive (0.00s)
--- PASS: TestNewRunnerPodForCR/Test_Negative-1 (0.00s)
--- PASS: TestNewRunnerPodForCR/Test_Negative-2_ (0.00s)
--- PASS: TestNewRunnerPodForCR/Test_Negative-3_ (0.00s)
=== RUN   TestNewMonitorServiceForCR
=== RUN   TestNewMonitorServiceForCR/Test_Positive
=== RUN …
```

Implemented unit test for chaosengine_controller

---

pkg/controller/chaosengine/chaosengine_controller.go
pkg/kubernetes/containers/build.go

- Introduces a builder function to set the image pull policy
- Set the image policy to IfNotPresent in the chaos-runner container spec 
**Checklist:**

(refactor)controller: provide image pull policy builder function

---

pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/types.go

Signed-off-by: chandan kumar <chandan.kumar@mayadata.io>
This commit will do the following changes:
- Refactor the ChaosEngine controller
- Create a file define all variable used in ChaosEngine controller
-  Typo fix of the function and variable name
**Checklist:**

(refactor)controller: Refactor the chaos engine controller package

---

.bettercodehub.yml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
pkg/controller/chaosengine/chaosengine_controller.go

(BCH): Excluded auto generated files form BCH check

---

pkg/controller/chaosengine/chaosengine_controller.go

- Passes app/chaosengine namespace to exporter in order to enable it to access experiment list
**Checklist:**

(fix)controller: pass app/chaosengine ns to exporter

---

pkg/controller/chaosengine/chaosengine_controller.go

Change Image Name in Runner

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

- Removing status sub resource from the chaosengine CRD
**Checklist:**

Removing status sub resource from the chaosengine CRD

---

.circleci/config.yml
buildscripts/push

(chore)ci: update circleci to push tagged images

---

.circleci/config.yml

- Makes changes to circle-ci config based on comments here: https://discuss.circleci.com/t/builds-for-tags-not-triggering/17681/6
- CircleCI does an OR operation on all filters, so build and push jobs will continue to run for all branch commits, while release job runs only on tags
**Checklist:**

(chore)ci: ensure circle ci builds for tags

---

.circleci/config.yml
buildscripts/push
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

Cherry Picking commits

---

cmd/manager/main.go
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/types.go

(refactor): Refactor the chaosengine controller function

---

pkg/controller/chaosengine/chaosengine_controller_test.go

- This commit changes will fix the unit test fail issue caused by the PR: https://github.com/litmuschaos/chaos-operator/pull/74
**Which issue this PR fixes **: fixes https://github.com/litmuschaos/litmus/issues/886
**Checklist:**

fix(UT): Add image field in unit test

---

pkg/controller/resource/deployment.go
pkg/controller/resource/resource.go
pkg/controller/resource/statefulset.go

- Add support for inducing chaos for statefulset
**Which issue this PR fixes**  fixes: https://github.com/litmuschaos/litmus/issues/880
**Checklist:**

(feat): Add support for induce chaos of statefulset

---

pkg/controller/resource/deployment.go
pkg/controller/resource/statefulset.go

- Fix the logging issue
Logs of the issue:
```
{"level":"dpanic","ts":1573106317.882434,"logger":"controller_chaos-scheduler","msg":"odd number of arguments passed as key-value pairs for logging","ignored key":"d773a0a3-c88c-11e9-bbd8-0cc47ab587b8","stacktrace":"github.com/mayadata-io/chaos-scheduler/vendor/github.com/go-logr/zapr.handleFields\n\tsrc/github.com/mayadata-io/chaos-scheduler/vendor/github.com/go-logr/zapr/zapr.go:106\ngithub.com/mayadata-io/chaos-scheduler/vendor/github.com/go-logr/zapr.(*infoLogger).Info\n\tsrc/github.com/mayadata-io/chaos-scheduler/vendor/github.com/go-logr/zapr/zapr.go:70\ngithub.com/mayadata-io/chaos-scheduler/pkg/controller/resource.CheckDeploymentAnnotation\n\ …
```

(fix): Fix the logging issue

---

pkg/controller/types/types.go

Signed-off-by: Raj <mail.rajdas@gmail.com>
changing image tag from ci to latest
**Checklist:**

(fix): changing image tag from ci to latest

---

pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go

-  **update appinfo field in runner pod - previously it is using engine ns as app namespace.**
**Checklist:**

(fix): update appns field in runner-pod

---

.circleci/config.yml
buildscripts/push
deploy/operator.yaml
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/deployment.go
pkg/controller/resource/statefulset.go
pkg/controller/types/types.go

- The following commits are cherry-picked:
- Add unique label for exporter pod #85 
- (refactor)build: ensure 'latest' tag corresponds to release builds #86 
- Fix the logging issue #87 
- changing image tag from ci to latest #88 
- (fix): update appns field in runner-pod #89

[Cherry-pick the changes to 0.8.0]

---

LICENSE

-  Update the LICENSE file with copyright message
**Checklist:**

(security): Update the license file with Copyright message

---

deploy/operator.yaml
pkg/controller/chaosengine/chaosengine_controller.go

Updated operator.yml and added few comments

---

tests/bdd/bdd_test.go

- The ansible runner will be deprecated soon. This PR moves the BDD execution to the Go-runner
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #111 
**Checklist:**

(refactor): use go executor in chaos operator bdd

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
tests/bdd/bdd_test.go

- Adds missing properties with pattern matching where applicable
- Update the chaos_crds.yaml consolidated file with latest schema
- Contains updates to the chaosengine & chaosexperiment types based on above schema updates
- `spec.experiment.components` is defined w/ `omitempty` as there are many experiments that execute with defaults (optional envs), such as pod-delete, say
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/litmuschaos/litmus/issues/1081
**Checklist:**

(refactor): improve chaos crd schema validation

---

README.md

- Adds the BCH badge to chaos-operator README
- Removes CII badge -- as it is better represented at a project level than a component level! 
**Checklist:**

(chore): add bch badge for chaos-operator

---

README.md
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
tests/bdd/bdd_test.go

- (refactor): improve chaos crd schema validation #115
- (chore): add bch badge for chaos-operator #116

[Cherry-pick for RC2]

---

.gitlab-ci.yml

Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>
- This is pr is for adding the baseline stage in the gitlab pipeline to record commits in the baseline file.
**Checklist:**

(feat): Add baseline stage in the gitlab pipeline

---

README.md

- This commit will fix the issue with the codacy badge

(Badge): Fix the codacy badge status

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/types/types.go

- Added annotationCheck as [true/false] in chaosengine spec.
- Removed chaosType from engine.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/litmuschaos/litmus/issues/1176
**Checklist:**

(Enhancement): Added annotationCheck [true/false] in chaosengine

---

.gitlab-ci.yml

- Fix the Gitlab-ci yaml format.
**Checklist:**

(fix): Fixing the Gitlab-ci YAML format

---

README.md

- Removes the helm-based instructions to install litmus, as the helm charts are deprecated
- Updates the README with latest engine/experiment schema
**Checklist:**

(refactor) remove helm instructions in the readme

---

pkg/controller/chaosengine/chaosengine_controller.go

(chore) Making Go Executor as Default Chaos Runner

---

pkg/controller/chaosengine/chaosengine_controller.go

- Added removal of Jobs, with similar engineUID
**Checklist:**

(fix) Added removal of Jobs having the engineUID

---

pkg/controller/chaosengine/chaosengine_controller.go

- Fixing Deletion Propagation Policy for resources
**Checklist:**

(fix) Delete Policy of Job fixed

---

pkg/controller/chaosengine/chaosengine_controller.go

- Update `engineUID` to `chaosUID` for passing labels
**Checklist:**

(refactor): Updated engineUID to chaosUID

---

README.md
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/watcher/watcher.go

(feat) Added logic to delete multiple Chaos resources

---

pkg/controller/chaosengine/chaosengine_controller.go

(fix) Added graceperiod argument, for deletion of resources

---

pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/controller/chaosengine/chaosengine_controller.go

(fix) Added Reconcile for empty engineStatus Spec

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

(feat): Adding crd valaidation for engineState

---

pkg/controller/chaosengine/chaosengine_controller.go
tests/bdd/bdd_test.go

- Added logic to delete engine Services
https://github.com/litmuschaos/litmus/issues/1207
**Checklist:**

(fix) chaos-operator: Managed Finalizers and Events

---

pkg/controller/chaosengine/chaosengine_controller.go

- Updated event reasons and messages from chaos-operator
**Checklist:**

(chore) Updated Events Reasons and Messages

---

pkg/controller/chaosengine/chaosengine_controller.go

- Have updated the events for reconcileForComplete 
**Checklist:**

(fix) Updated strings for completed Chaos Engine Event

---

tests/bdd/bdd_test.go

- Have updated the BDD testcase
- Now, we patch the engine wit stop state, too check for resource deletion
- Added a new Case, where the experiment name is wrong, so created resources will be terminated instantly.
- https://github.com/litmuschaos/chaos-operator/issues/170
**Checklist:**

(chore) Updated BDD for Abort Functionality

---

pkg/controller/chaosengine/chaosengine_controller.go

(fix) Added logic to handle Deletion of ChaosEngine in Completed Status

---

NOTICE.md

- Add a notice file pertaining to licenses
**Checklist:**

(chore)notice: add notice file

---

.circleci/config.yml
Makefile

Signed-off-by: Chandan Kumar <chandan.kr404@gmail.com>
- This PR will integrate the codecov which will generate the coverage report
**Checklist:**

(codecov): Integrate codecov coverage

---

.circleci/config.yml
Makefile
NOTICE.md
README.md
pkg/controller/chaosengine/chaosengine_controller.go
tests/bdd/bdd_test.go

- Includes the following commits:
- https://github.com/litmuschaos/chaos-operator/pull/174/commits/192a95e87905ac069148ade3f912cda0690dedcd
- https://github.com/litmuschaos/chaos-operator/pull/174/commits/43f2ceb189078bf639915f4c41f9dc397f3e22bd
- https://github.com/litmuschaos/chaos-operator/pull/174/commits/d2c4ee7568945bf082ee4b7df50849b55bf2fbae
- https://github.com/litmuschaos/chaos-operator/pull/174/commits/e2b765d55dd2dfac73a4d65d37d74235846f7fdd
- https://github.com/litmuschaos/chaos-operator/pull/174/commits/7041e3a9d8ab9975e3380ffac06ce13709a14aa2
- https://github.com/litmuschaos/chaos-operator/pull/174/commits/e3746943e2c092b38f93b04a6aae097db2a12e98
- https://github.com/litmuschaos/chaos-operator/pull/174/commits/6ed44fc4f86e047ca254617ba …

[Cherry pick for 1.2.0] 

---

pkg/controller/resource/resource.go

- Have added support for custom annotation, with key being custom, but the value still being "true"/"false" to validate the application
- https://github.com/litmuschaos/litmus/issues/1252
- Have added comments to show, how it works.
**Checklist:**

(feat) Added support for Custom Annotation

---

pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go

- Added ENGINE_NAMESPACE ENV in chaos-runner
https://github.com/litmuschaos/litmus/issues/1219
**Checklist:**

(feat) Added new CHAOS_NAMESPACE env in chaos-runner for adminMode

---

pkg/controller/chaosengine/chaosengine_controller.go

https://github.com/litmuschaos/litmus/issues/1356
**Checklist:**

(feat) Added failure events for ChaosEngine

---

pkg/controller/chaosengine/chaosengine_controller.go

- Fixed Monitor Service Labels
**Checklist:**

(fix) Changed the labelSelector for monitor Service

---

README.md

(chore) Added CodeCov Badge for Chaos-operator

---

deploy/01-chaos-operator.yaml
deploy/02-annotated-nginx-deploy.yaml
deploy/03-pod-delete-experiment.yaml
deploy/04-rbac-manifest.yaml
deploy/05-chaos-engine.yaml
deploy/README.md
deploy/crds/chaosengine.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml

- Fixed approriate YAML's in deploy folder
- https://github.com/litmuschaos/litmus/issues/1393
**Checklist:**

(fix) Updated YAML's in deploy folder

---

README.md
deploy/01-chaos-operator.yaml
deploy/02-annotated-nginx-deploy.yaml
deploy/03-pod-delete-experiment.yaml
deploy/04-rbac-manifest.yaml
deploy/05-chaos-engine.yaml
deploy/README.md
deploy/crds/chaosengine.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
pkg/analytics/analytics.go
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/resource.go

- Includes the following commits: 
aab59dfc175318168245148f1ceed9c5e174ef96
702971322b6fc4a6de5f2a1f96d113ace2c1c3f4
9cdb62ebe26aa10b53306220d6148f950dd073c4
20cbcb98e55f3fe57f33cd1a5a52177226636f08
91bfc081545b936638b25709a4906e8783ca82da
ebf41ba532ce3c128782065830e37dbe50b33353
61185d834e55811c74428b4dab4d3dd614584a49
1e7062571896f06ecfa8da3e72f7b45bf89378f6
**Checklist:**

[Cherry pick for 1.2.2] 

---

pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/daemonset.go
pkg/controller/resource/deployment.go
pkg/controller/resource/resource.go
pkg/controller/resource/statefulset.go

(refact/feat) Refactor reconcile function of chaos-operator, added engine restart logic

---

.circleci/config.yml

Signed-off-by: Raj <raj.das@mayadata.io>
Adding Trivy check to CircleCI
**Checklist:**

(Feat): Adding Trivy check to CircleCI

---

.circleci/config.yml

Signed-off-by: Raj <raj.das@mayadata.io>
**Checklist:**

adding the rpm command

---

.circleci/config.yml

Cherry-picked commit:
- Adding trivy (#185) 
- adding the rpm command (#192) …

Cherry pick for v1.3.x

---

.github/CODEOWNERS

(chore) Adding CODEOWNERS

---

Gopkg.lock
Gopkg.toml
deploy/chaos_crds.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
vendor/github.com/litmuschaos/elves/kubernetes/pod/build.go

(chore) Updated Vendor with latest changes

---

pkg/controller/chaosengine/chaosengine_controller.go

- This PR is a fix for underlying issue.
https://github.com/litmuschaos/litmus/issues/1481
**Checklist:**

(fix) fixed reconcile error issue, and added error strings

---

deploy/01-chaos-operator.yaml

Signed-off-by: Raj <raj.das@mayadata.io>
- Admission controller resource permission
**Checklist:**

Admission controller resource permission

---

deploy/01-chaos-operator.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
deploy/crds/chaosresults_crd.yaml

Fixed syncing CRD's in deploy/*.yaml

---

deploy/01-chaos-operator.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
deploy/crds/chaosresults_crd.yaml
pkg/controller/chaosengine/chaosengine_controller.go

Cherry-picked commit:
* (fix)controller: propagate annotaion check failure to reconciler (#212)
* Fixed syncing CRD's in deploy/*.yaml (#210)

Latest Cherry-pick for v1.4.x

---

pkg/controller/chaosengine/chaosengine_controller.go

Latest cherry-pick for v1.3.x

---

pkg/controller/chaosengine/chaosengine_controller_test.go

test(unit-tests): Adding unit tests for the engine controller

---

pkg/controller/resource/resource_test.go

Signed-off-by: Raj Das <mail.rajdas@gmail.com>
- Adding unit test case for resource pkg
**Checklist:**

chore(test): Adding unit test case for resource pkg

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
deploy/README.md

fix(codacy): Fixing the codacy issue

---

Makefile

Signed-off-by: Raj Das <raj.das@mayadata.io>
Adding unused package check for the chaos-operator
**Checklist:** …

chore(Makefile): Adding unused package check for the chaos-operator

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes litmuschaos/litmus#1635
**Checklist:**
-   [x] Fixes  litmuschaos/litmus#1635 …

update(image): override the chaos experiment image from chaos engine

---

pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/zz_generated.deepcopy.go

- Adds nodeSelector to ChaosEngine spec 
- Added in partial fulfillment of issue https://github.com/litmuschaos/litmus/issues/1240
**Checklist:**
-   [ ] PR messages …

(enhancement)engine_types: add nodeSelector to experiment component spec

---

pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
pkg/apis/litmuschaos/v1alpha1/zz_generated.deepcopy.go

- Takes a list of host files for mount over a single mount
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # (partially fulfills https://github.com/litmuschaos/litmus/issues/1650)
- Refer: https://github.com/litmuschaos/chaos-runner/pull/72
**Checklist:**
-   [ ] Labelled this PR & …

(enhancement)types: take a list of hostFileVolumes

---

deploy/chaos_crds.yaml
deploy/crds/chaosexperiment_crd.yaml

update(crds): updating the chaos experiment crds

---

go.mod
go.sum
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes litmuschaos/litmus#1474
**Checklist:**
-   [x] Fixes litmuschaos/litmus#1474 …

feat(istio): Adding support to run in istio enabled mode

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml

feat(openeapi): Adding the openapi validations

---

deploy/01-chaos-operator.yaml
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/controller/chaosengine/chaosengine_controller.go

https://github.com/litmuschaos/chaos-operator/commit/2ea2f42adbaed0fc0270d7a1757d6ac64e747f09
**Checklist:**
-   [ …

[Cherry-pick for 1.6.2]

---

pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go

update(chaosresult): Updating the chaosresult_types.go file

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

update(crds): updating the chaosengine crd

---

.circleci/config.yml
Makefile

- Update the image tags for the dev branch
**Checklist:** …

(chore)build: update image tags for dev branch

---

buildscripts/push

Minor Fix/Add correct push command for multi-arch

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go

- Adding the `labelSelector` attribute inside k8sProbe which can be used to filter the resource based on label selectors.
**Checklist:**
-   [ ] PR …

chore(k8sprobe): Adding label-selector field in k8sprobe

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go

Commits:
- 1dcf31d755f0522292847a90a7a40943d3e24663

cherry-pick for 1.8.1

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/zz_generated.deepcopy.go
pkg/controller/chaosengine/chaosengine_controller.go

- 96f58f40a7192dfc78fdc26da6f49f93a0900fb0
- 8805f49fa9cfd674a01835c737b902b4f5b35a6d
**Checklist:**
-   [ ] Commit has integration …

[cherry-pick]: V1.8.x tracker

---

deploy/operator.yaml
deploy/rbac.yaml

Add recommanded labels into manifests files
Cf: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
**Checklist:** …

Add: recommanded Kubernetes labels

---

tests/bdd/bdd_test.go

- Wait for appropriate runner status
- Change experiment spec to use go-runner
**Checklist:** …

(fix)bdd: fix bdd tests

---

pkg/analytics/uuid.go

chore(analytics): pass client-uuid as blank if analytics is false

---

pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/resource.go

- Adding support for multi-app deploy. Need to pass the annotation parameters to runner/experiment pod. It will choose the annotationed pod only if annotation check is set to true.
**Checklist:**
-   [ ] Labelled this …

chore(annotation): multi app annotation support

---

deploy/operator.yaml
deploy/rbac.yaml
pkg/controller/chaosengine/chaosengine_controller.go

chore(operator): updating operator manifest

---

build/Dockerfile
pkg/controller/chaosengine/chaosengine_controller_test.go

- This PR is for reducing the current chaos-operator image size.
- Fix the broken circle ci.
**Checklist:**
- …

enhanc(image): Reduce Operator image size

---

CONTRIBUTING.md
hack/update-codegen.sh

Signed-off-by: Chandan Kumar <chandan.kumar@mayadata.io>
This commit will contain the following changes
- Update the steps to generating the auto-generated code via k8s.io/code-generator
- Added the steps in CONTRIBUTION.md for generating the auto-generated code
**Checklist:**
-   [x] PR messages has document related information
-   [ ] Commit …

Docs(Contribution_guideline): update the contribution guideline for generating the auto-generated code

---

pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/zz_generated.deepcopy.go
pkg/controller/chaosengine/chaosengine_controller.go

chore(resources): Adding resource requirements for runner pod

---

pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go

chore(promProbe): Adding queryPath in prom probe

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml

chore(openapi): update the openapi validation for crds

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/controller/chaosengine/chaosengine_controller.go

* (fix)reconcile: fix incorrect sequence of events for engine restart
* (fix)reconcile: separate reconcile ops for graceful completion and abort cases
* (chore)info: enhance logs, event reasons and comments in reconcile function
* (refactor)enginestate: remove redundant values for enginestate in crd validation
**Checklist:**
-   [ ] …

[Cherry-pick for v1.11.2]

---

pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go

(enhance)httpProbe: add support for insecure verify in the httpProbe

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

(chore)crd: enhance validation for httpProbe

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go

[Cherry-pick for 1.11.3]

---

deploy/chaos_crds.yaml
deploy/crds/chaosexperiment_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go

!--  Thanks for sending a pull request!  Here are some tips for you -->
https://github.com/litmuschaos/chaos-operator/pull/325/commits/0f051a2939729d04bc04b4b268288e7215988382
**Checklist:** …

[Cherry pick for 1.12.1]

---

go.sum
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/argorollouts.go
pkg/controller/resource/daemonset.go
pkg/controller/resource/deployment.go
pkg/controller/resource/deploymentconfig.go
pkg/controller/resource/resource.go
pkg/controller/resource/resource_test.go
pkg/controller/resource/statefulset.go
pkg/controller/types/types.go

- 346f29188fb4e042e23d50d6e3a37fcdd8b933f2
**Checklist:**
-   [ ] …

[Cherrypick for 1.12.2]

---

pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/resource_test.go

update(unit-tests): updating unit-tests

---

pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/resource_test.go

test(unit-tests): updating unit tests

---

pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/resource_test.go

[Cherry Pick Unit tests fix 1.12.x]

---

pkg/controller/chaosengine/chaosengine_controller.go

- Pull #336 into v1.12.x for 1.12.3 patch release
**Checklist:** …

(fix)controller: remove force flag (gracePeriodSeconds: 0) for abort cases

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go
pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go
pkg/controller/resource/resource_test.go
tests/bdd/bdd_test.go

- fbd02f3f1cd720b9eaa078242c0dffba663f3d86
- 50a357ad2256f079a860188aa9628c52590c4110
- dd484bbadfb9e3a8293b2fef68045e949eb09f38
**Checklist:** …

[ cherrypick for 1.13.3]

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
deploy/crds/chaosresults_crd.yaml

- updating crds apiVersion to v1
**Checklist:** …

chore(crds): updating crds apiVersion to v1

---

.circleci/config.yml

update(k8s): updating kubernetes version

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml

updating the crds for the unknown fields
**Checklist:** …

chore(crds): updating the crds for the unknown fields

---

pkg/controller/types/types.go

- converting default annotation check to false
**Checklist:**
-   [ ] …

chore(annotation): converting default annotation check to false

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

crds(validation): Adding openapi validation for tolerations

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml
deploy/crds/chaosexperiment_crd.yaml
pkg/controller/types/types.go

- https://github.com/litmuschaos/chaos-operator/commit/3197734ae4355526dc9da2143d1ebf7129ef9fba
- https://github.com/litmuschaos/chaos-operator/commit/91e354b52b654f79a2aef5d48c35ec9451989a10
- https://github.com/litmuschaos/chaos-operator/pull/362/commits/bbcb03ad8dc7b4687f370d7b76f53c98d8738053
**Checklist:** …

[Cherry-Pick for 1.13.5]

---

pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go
pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go

-  updating verdict and status in chaosengine and chaosresult
**Checklist:**
-   [ ] Commit has unit …

chore(chaosresult): updating verdict and status in chaosengine and chaosresult

---

pkg/apis/litmuschaos/v1alpha1/chaosresult_types.go
pkg/controller/chaosengine/chaosengine_controller.go
pkg/controller/chaosengine/chaosengine_controller_test.go

-  Renaming the target name in chaosresults
**Checklist:**
-   [ ] Commit …

chore(targets): Renaming the target name in chaosresults

---

deploy/operator.yaml
pkg/controller/chaosengine/chaosengine_controller.go

- skipping crd validation for the namespace-scoped operator
- adding downward API ENV for the operator ns which will be used in analytics
**Checklist:**
- …

chore(crd): skipping crd validation for the namespace-scoped operator

---

.github/workflows/build.yml
Makefile
deploy/operator.yaml
pkg/controller/chaosengine/chaosengine_controller.go

It consists of following commits:
- 4d84f78adead4974615533df15331178941a1084
- 2839dffa7cb27b76f4c0d40f35dbc923f414c5f6
**Checklist:**
-   [ ] Commit has unit …

[cheerypick for 2.0.0-RC-1]

---

pkg/controller/resource/deploymentconfig.go

Signed-off-by: Chandan Kumar <chandan.kr404@gmail.com>
- Add the nil check for deployment configs
**Checklist:**
-   [x] Fixes https://github.com/litmuschaos/chaos-operator/issues/202
-   [ ] …

Add the nil check for deploymentconfigs

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

adding openapi validation for default app health check

---

deploy/chaos_crds.yaml
deploy/crds/chaosexperiment_crd.yaml

Adding valueForm field for the ENVs inside chaosexperiment CRD 
**Checklist:**
-   [ ] Commit has unit …

chore(crd): adding valueFrom field inside env

---

deploy/chaos_crds.yaml
deploy/crds/chaosexperiment_crd.yaml
tests/bdd/bdd_test.go

fix(bdd): fixing the bdd

---

go.sum

updating go modules

---

.github/workflows/build.yml
.github/workflows/push.yml
.github/workflows/release.yml
deploy/rbac.yaml
tests/bdd/bdd_test.go
tests/manifest/pod_delete_rbac.yaml

Chore(rbac): Update litmus rbac to version v1 from v1beta1

---

.github/workflows/build.yml

- Fix snyk security scan on chaos-operator
**Checklist:** …

Chore(snyk): Fixes snyk security scan on chaos-operator

---

build/Dockerfile

Chore(build): Fix the go build by providing -buildvcs=false flag

---

.gitignore
deploy/operator.yaml
main.go

chore(leader-elect): enabling leader-elect for multiple replicas

---

deploy/rbac.yaml

- Fix permissions for leader election in chaos-operator
**Checklist:**
-   [ ] …

Chore(permission): Fix permissions for leader election in chaos-operator

---

api/litmuschaos/v1alpha1/chaosengine_types.go
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

…imeout field instead
**Checklist:**
-   [ ] Commit has integration …

chore(httpProbe): Remove responseTimeout field, use the global probeTimeout field instead

---

api/litmuschaos/v1alpha1/chaosengine_types.go
api/litmuschaos/v1alpha1/zz_generated.deepcopy.go
controllers/chaosengine_controller.go
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

chore(runnerLabels): Adding support for custom labels in chaos-runner

---

deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

chore(probe): changing min runpropeties attributes to 2

---

controllers/chaosengine_controller.go
controllers/chaosengine_controller_test.go

fix(reconcile): fixing the reconcile logs and events

---

.github/workflows/build.yml
api/litmuschaos/v1alpha1/chaosresult_types.go

chore(verdict): Adding awaited verdict as enum

---

main.go

fix(analytics): fixing analytics

---

main.go

fix(operator): fixing setup logging

---

controllers/chaosengine_controller.go
controllers/chaosengine_controller_test.go

chore(operator): fixing the update conflict issue

---

api/litmuschaos/v1alpha1/chaosresult_types.go

feat(errorCode): Adding error code inside chaosresult

---

api/litmuschaos/v1alpha1/chaosengine_types.go
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

chore(probe): updating retries to attempt

---

api/litmuschaos/v1alpha1/chaosengine_types.go
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

Adding backend compatibility to probe retry

---

api/litmuschaos/v1alpha1/chaosresult_types.go

add the experiment phase as completed with error

---

api/litmuschaos/v1alpha1/chaosresult_types.go

updating result phase

---

api/litmuschaos/v1alpha1/chaosengine_types.go
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

Added insecureSkipVerify in SLO Probe

---

api/litmuschaos/v1alpha1/chaosengine_types.go
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

Updated insecure skip verify type

---

api/litmuschaos/v1alpha1/chaosengine_types.go
deploy/crds/chaosengine_crd.yaml

Add initialDelaySeconds for backward compatibility of probes

---

pkg/client/clientset/versioned/typed/litmuschaos/v1alpha1/fake/fake_chaosengine.go
pkg/client/clientset/versioned/typed/litmuschaos/v1alpha1/fake/fake_chaosexperiment.go
pkg/client/clientset/versioned/typed/litmuschaos/v1alpha1/fake/fake_chaosresult.go

fixing the group of the fake clients

---

.github/workflows/build.yml
.github/workflows/e2e.yml
.github/workflows/push.yml
.github/workflows/release.yml
go.mod

Upgrading the go version in build files to 1.20 to fix the vulnerabilities
**Checklist:**

Upgrading the go version in build files

---

Makefile
deploy/operator.yaml

Integrate the operator image with scarf gateway

---

go.mod
go.sum

fix the go deps

---

api/litmuschaos/v1alpha1/chaosengine_types.go
deploy/chaos_crds.yaml
deploy/crds/chaosengine_crd.yaml

This PR adds verbosity Property in run properties as part of the [PR](https://github.com/litmuschaos/litmus-go/pull/676)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #https://github.com/litmuschaos/litmus-go/issues/678
**Checklist:** …

Adds verbosity property

---

api/litmuschaos/v1alpha1/chaosengine_types.go

fix(logs): fix the rank warning in logs

---

.github/workflows/release.yml

(chore): Fix the release pipelines
